---
framework: mocha
preRun:
     command:
        - npm install
preMerge:
  pattern:
    - "./test/**/*_test.js"
postMerge:
  pattern: 
    - "./test/**/*_test.js"
postRun:
     command:
        - node --version
# configFile: mocharc.yml
version: 1.0